#!/bin/sh -l
# FILENAME:  submit.cmd

#SBATCH -A <PROJECT_ID>
#SBATCH -p wholenode # the default queue is "shared" queue
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=128
#SBATCH --time=00:30:00
#SBATCH --job-name dedalus2
#SBATCH --output="dedalus.o%j"
#SBATCH --error="dedalus.e%j"

module load fftw/3.3.8
module load hdf5/1.10.7
module load anaconda
conda activate dedalus2

# Print the hostname of the compute node on which this job is running.
hostname
mpiexec -n 256 python3 rayleigh_benard.py
